server:
  port: 9966

spring:
  application:
    name: administracion-usuarios  # Service registers under this name

  #Datasource and JPA configuration
  datasource:
    url: oracle:jdbc:thin:@localhost:49161:XE
    username: PERFUMERIA
    password: PERFUMERIA
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false